sudo: required
services:
  - docker

before_install:
  - docker build -t kidnohr2000/docker-react -f Dockerfile.dev .

script:
  - docker run -e "CI=true" kidnohr2000/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-ap-northeast-1-439513548571"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"